config/routes.rb
Events::Application.routes.draw do
  root "events#index"
  # get "events" => "events#index"
  # get "events/new" => "events#new", as: "new_event"
  # get "events/:id" => "events#show", as: "event"
  # get "events/:id/edit" => "events#edit", as: "edit_event"
  # patch "events/:id/" => "events#update"
  resources :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  def free?
    price.blank? || price.zero?
  end

  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    # @events = Event.all
    @events = Event.where("starts_at >= ?", Time.now).order("starts_at")
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to @event
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to @event
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end
private

  def event_params
   params.require(:event).
     permit(:name, :description, :location, :price, :starts_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def formated_price(event)
    if event.free?
      content_tag(:strong, "Free!")
    else
      number_to_currency(event.price, format: "%n %u", delimiter: " ", unit: "LT", precision: 0)
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :location %><br/>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :starts_at %><br/>
    <%= f.datetime_select :starts_at %>
  </p>
  <p><%= f.submit %>
  <%= link_to 'Cancel', events_path %>
  </p>
  <% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1><%= pluralize(@events.size, 'Event') %></h1>
<nav><%= link_to 'Add New Event', new_event_path %></nav>
<p>Check out the following <%= pluralize(@events.size, 'event') %>:</p>


<% @events.each do |event| %>
  <article>
    <header>
      <h2><%= link_to event.name, event %></h2>
    </header>
    <p><%= truncate(event.description, length: 35, separator: " ") %></p>
    <table>
      <tr>
        <th>When:</th>
        <td><%= event.starts_at %></td>
      </tr>
      <tr>
        <th>Where:</th>
        <td><%= event.location %></td>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= formated_price(event) %></td>
      </tr>
    </table>
  </article>
<% end %>

app/views/events/new.html.erb
<h1>Creating a new event</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<article>
  <header>
  <h1><%= @event.name %></h1>
  </header>
  <p><%= @event.description %></p>
  <h3>When</h3>
  <p><%= @event.starts_at %></p>
  <h3>Where</h3>
  <p><%= @event.location %></p>
  <h3>Price</h3>
  <p><%= formated_price(@event) %></p>
</article>
<%= link_to 'Edit', edit_event_path %> |
<%= link_to 'Delete', event_path(@event), method: :delete, data: {confirm: 'Are you sure?'} %> |
<%= link_to "All Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>